### ISSUE TITLE
Some emojis are not recognized

### ISSUE THREAD

**Issue by zachary-mcdargh** [whitead/emoji-math#1]
It seems like the king, and groucho marx emojis are not recognized, and interpreted as regular text. Examples below:

`    import numpy as np; result = 🤴-emoji2vec["👸"]+emoji2vec["👩"]
                                 ^
SyntaxError: invalid character in identifier
`

`    import numpy as np; result = emoji2vec["😎"]-🥸
                                                ^
SyntaxError: invalid character in identifier
`

**Comment by whitead** [comment]
Fixed by f836d9b5f2b4c4b4d951e9026a6e676238ff57d5
